AllCops:
  Exclude:
    - files/default/vendor/**/*
    - vendor/bundle/**/*

Lint/AmbiguousOperator:
  Exclude:
    - 'libraries/_autoload.rb'

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - '**/test/**/*'
